import streamlit as st
import pandas as pd
import plotly.express as px
import json
import folium
from streamlit_folium import st_folium
import random


# ---------------- CONFIG ---------------- #

st.set_page_config(
    page_title="India District Development Index",
    layout="wide"
)



# ---------------- STYLE ---------------- #

st.markdown(
"""
<style>

.main{
    background:#f7f9fc;
}


.card{
    background:white;
    padding:20px;
    border-radius:18px;
    box-shadow:0 4px 12px rgba(0,0,0,0.08);
    text-align:center;
}


.big{
    font-size:32px;
    font-weight:700;
}


.small{
    color:#666;
}


</style>
""",
unsafe_allow_html=True
)




# ---------------- LOAD ---------------- #

@st.cache_data
def load_data():

    ddi = pd.read_csv(
        "data/processed/district_development_index.csv"
    )

    ddi["State"]=ddi["State"].str.strip()
    ddi["District"]=ddi["District"].str.strip()
    ddi["Year"]=ddi["Year"].astype(int)

    return ddi



ddi = load_data()



@st.cache_data
def load_geojson():

    with open(
        "data/geojson/india_district.geojson",
        encoding="utf-8"
    ) as f:

        return json.load(f)



geojson=load_geojson()




# ---------------- HERO ---------------- #

facts=[

"India's district GDP analysis helps identify economic inequality.",
"High GDP does not always mean high development.",
"DDI combines GDP and growth behaviour to estimate development.",
"District-level insights support targeted planning.",
"Economic growth varies significantly between regions.",
"Long term trends reveal structural economic changes.",
"Urban districts usually contribute a large share of GDP.",
"Growth rate measures economic acceleration.",
"Development is a combination of size and progress.",
"Data helps transform policy decisions."

]


st.title(
"🇮🇳 India District Development Index"
)


st.subheader(
"Tracking economic growth and development across districts"
)


c1,c2,c3=st.columns(3)


with c1:
    st.info(random.choice(facts))


with c2:
    st.success(
        f"""
        📍 {ddi['District'].nunique()}
        
        Districts analysed
        """
    )


with c3:
    st.warning(
        """
        📅 1999-2012
        
        Economic period covered
        """
    )



with st.expander("📘 About the Dashboard"):

    st.write(
"""
**GDP (Rs. Crore)**  
Economic output generated by a district.

**Growth Rate (%)**  
Year-on-year change in GDP.

**DDI**  
Composite score representing district development.

Higher DDI indicates stronger relative development.
"""
)





# ---------------- FILTERS ---------------- #

st.header("🎛️ Select Analysis")


a,b,c=st.columns(3)


with a:

    state=st.selectbox(
        "State",
        sorted(ddi.State.unique())
    )


with b:

    years=sorted(
        ddi[
        ddi.State==state
        ].Year.unique()
    )


    year=st.slider(
        "Year",
        min(years),
        max(years),
        max(years)
    )


data=ddi[
    (ddi.State==state)
    &
    (ddi.Year==year)
]


with c:

    district=st.selectbox(
        "District",
        sorted(data.District.unique())
    )

# ---------------- RANKING ---------------- #

data=data.copy()


# State rank
state_rank = (
    ddi[
    (ddi.Year==year) &
    (ddi.State==state)
    ]
    .sort_values(
        "DDI",
        ascending=False
    )
    .reset_index(drop=True)
)

state_rank["Rank"]=state_rank.index+1


state_rank_value=int(
    state_rank[
    state_rank.District==district
    ].Rank.iloc[0]
)



# India rank
india_rank = (
    ddi[
    ddi.Year==year
    ]
    .sort_values(
        "DDI",
        ascending=False
    )
    .reset_index(drop=True)
)

india_rank["Rank"]=india_rank.index+1


india_rank_value=int(
    india_rank[
    india_rank.District==district
    ].Rank.iloc[0]
)

selected=data[
    data.District==district
].iloc[0]

ddi_value=selected.DDI

# percentile among all districts for selected year

percentile = (
    ddi[
        ddi.Year==year
    ]["DDI"]
    .rank(pct=True)
    .loc[
        ddi[
        (ddi.Year==year) &
        (ddi.District==district)
        ].index[0]
    ]
)


if percentile>=0.75:
    category="🟢 High Development"

elif percentile >=0.5:
    category="🟡 Medium Development"

else:
    category="🔴 Low Development"


# ---------------- METRICS ---------------- #

st.header("📊 District Overview")


# First row - main indicators
m1,m2,m3,m4 = st.columns(4)


metrics1=[
("💰 GDP",f"₹ {selected.GDP:,.0f} Cr"),
("📈 Growth",f"{selected.GrowthRate:.2f}%"),
("🏆 State Rank",f"#{state_rank_value}"),
("🏆 In India Rank",f"#{india_rank_value}")
]


for col,(x,y) in zip(
    [m1,m2,m3,m4],
    metrics1
):

    with col:

        st.markdown(
        f"""
        <div class="card">

        <div class="small">{x}</div>

        <div class="big">
        {y}
        </div>

        </div>
        """,
        unsafe_allow_html=True
        )



# Second row - development indicators

m4,m5 = st.columns(2)


metrics2=[
("📊 DDI Score",f"{ddi_value:.3f}"),
("🏷️ Category",category)
]


for col,(x,y) in zip(
    [m4,m5],
    metrics2
):

    with col:

        st.markdown(
        f"""
        <div class="card">

        <div class="small">{x}</div>

        <div class="big">
        {y}
        </div>

        </div>
        """,
        unsafe_allow_html=True
        )








# ---------------- CHARTS ---------------- #

st.header("📈 Economic Performance")


trend=ddi[
    ddi.District==district
]


g1,g2=st.columns(2)



with g1:

    fig=px.line(
        trend,
        x="Year",
        y="GDP",
        markers=True,
        title="GDP Growth Trend (₹ Crore)"
    )

    fig.update_layout(height=350)

    st.plotly_chart(
        fig,
        use_container_width=True
    )




with g2:

    fig2=px.bar(
        trend,
        x="Year",
        y="GrowthRate",
        title="Yearly Growth Rate (%)"
    )

    fig2.update_layout(height=350)


    st.plotly_chart(
        fig2,
        use_container_width=True
    )







# ---------------- INSIGHT ---------------- #

st.header("🧠 Automated Insights")


latest=trend.sort_values("Year").iloc[0]
current=trend.sort_values("Year").iloc[-1]


increase=(
    (current.GDP-latest.GDP)
    /
    latest.GDP
)*100



st.write(
f"""
• {district} GDP increased by approximately **{increase:.1f}%** over the available period.

• Current DDI score is **{ddi_value:.3f}**.

• The district currently ranks **#{state_rank_value}** among districts of {state}.

• The district currently ranks **#{india_rank_value}** in India.

• Current development category: **{category}**
"""
)






# ---------------- TABLE ---------------- #

st.header("🏆 District GDP Ranking")


top=data.sort_values(
    "GDP",
    ascending=False
).head(10)



low=data.sort_values(
    "GDP"
).head(10)



x,y=st.columns(2)


with x:

    st.subheader("Top 10 GDP Districts")

    st.dataframe(
        top[
        ["District","GDP","GrowthRate","DDI"]
        ],
        hide_index=True,
        use_container_width=True
    )



with y:

    st.subheader("Lowest 10 GDP Districts")

    st.dataframe(
        low[
        ["District","GDP","GrowthRate","DDI"]
        ],
        hide_index=True,
        use_container_width=True
    )







# ---------------- MAP ---------------- #

st.header("🗺️ India District Development Map")



map_df=ddi[
    ddi.Year==year
].copy()


map_df["clean"]=(
    map_df.District
    .str.lower()
    .str.replace(" ","")
)


for f in geojson["features"]:

    name=f["properties"].get(
        "NAME_2",""
    )

    f["properties"]["clean"]=(
        name.lower()
        .replace(" ","")
    )




m=folium.Map(
    location=[22.5,80],
    zoom_start=4
)



folium.Choropleth(
    geo_data=geojson,
    data=map_df,
    columns=[
        "clean",
        "DDI"
    ],
    key_on="feature.properties.clean",
    fill_opacity=0.75,
    legend_name="District DDI"
).add_to(m)



st_folium(
    m,
    width=1200,
    height=600
)
